# Generated by Django 3.1.6 on 2021-02-09 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('code', models.IntegerField(help_text='Код региона РФ', primary_key=True, serialize=False)),
                ('name', models.TextField(help_text='Наименование региона РФ', unique=True)),
            ],
            options={
                'verbose_name_plural': 'region',
            },
        ),
        migrations.CreateModel(
            name='Okved',
            fields=[
                ('code', models.TextField(help_text='Код ОКВЭД', primary_key=True, serialize=False)),
                ('name', models.TextField(help_text='Наименование ОКВЭД')),
                ('parent_code', models.ForeignKey(blank=True, db_column='parent_code', help_text='Родительский код ОКВЭД', null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.okved')),
            ],
            options={
                'verbose_name_plural': 'okved',
            },
        ),
        migrations.CreateModel(
            name='Okopf',
            fields=[
                ('code', models.IntegerField(help_text='Код ОКОПФ', primary_key=True, serialize=False)),
                ('name', models.TextField(help_text='Наименование ОКОПФ')),
                ('parent_code', models.ForeignKey(blank=True, db_column='parent_code', help_text='Родительский код ОКОПФ', null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.okopf')),
            ],
            options={
                'verbose_name_plural': 'okopf',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Полное русскоязычное название компании', unique=True)),
                ('inn', models.TextField(help_text='ИНН компании')),
                ('kpp', models.TextField(help_text='КПП компании')),
                ('registration_date', models.DateField(blank=True, help_text='Дата постановки на учет в налоговом органе', null=True)),
                ('email', models.EmailField(blank=True, help_text='Контактный email компании', max_length=254, null=True)),
                ('link', models.URLField(blank=True, help_text='Ссылка на веб-сайт компании', null=True)),
                ('okopf', models.ForeignKey(help_text='Организационно-правовая форма компании', on_delete=django.db.models.deletion.DO_NOTHING, to='companies.okopf')),
                ('region', models.ForeignKey(help_text='Регион компании', on_delete=django.db.models.deletion.DO_NOTHING, to='companies.region')),
            ],
            options={
                'verbose_name_plural': 'companies',
                'unique_together': {('inn', 'kpp')},
            },
        ),
    ]
